"""empty message

Revision ID: 0f967a2c353e
Revises: 046a7e921275
Create Date: 2024-07-22 19:25:39.825916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f967a2c353e'
down_revision = '046a7e921275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('planetId', sa.Integer(), nullable=False),
    sa.Column('planetName', sa.String(length=250), nullable=True),
    sa.Column('planetDescription', sa.String(length=2500), nullable=True),
    sa.PrimaryKeyConstraint('planetId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
